import json
D = {
585: ("Monografia ilustrada sobre a Quinta e o Palácio da Bacalhôa, em Azeitão, e os inícios da Renascença em Portugal (1898).", None),
225: ("Impressões de Wenceslau de Moraes sobre a China e o Japão, onde o autor viveu.", "Viagem"),
172: ("Garrett viaja de Lisboa a Santarém e conta, entre digressões, a história de Joaninha, a menina dos rouxinóis. Primeiro volume.", "Viagem"),
177: ("Garrett viaja de Lisboa a Santarém e conta, entre digressões, a história de Joaninha, a menina dos rouxinóis. Segundo volume.", "Viagem"),
335: ("A história de Portugal contada com leveza para o povo e as escolas, por Pinheiro Chagas (1880).", None),
349: ("Romance-crônica do século XIV passado no Porto, depois da morte de D. Fernando I.", None),
456: ("Alberto Pimentel analisa o temperamento de escritores a partir da ideia de que o gênio é uma nevrose.", None),
31: ("A crônica de D. Pedro I, rei de Portugal, escrita por Fernão Lopes, o maior cronista medieval português.", None),
429: ("S. de Magalhães Lima conta o 1.º de Maio e o movimento operário.", None),
3283: ("Romance de Emília Moncorvo Bandeira de Melo, que começa no casamento da Celina, num hotel familiar de Santa Teresa.", None),
345: ("Crônica do século XVII sobre Manuel de Morais, paulista que se uniu aos holandeses e acabou nas mãos da Inquisição.", None),
1695: ("Memórias de quarenta anos no interior do Brasil, com episódios da guerra do Contestado.", None),
1204: ("Contos do rabino Nachman de Breslau, como o da perda da filha da rainha.", None),
504: ("Quadros de salão em forma de flertes, por Henrique de Vasconcellos.", None),
2375: ("Estudo de Pietro Fornitano Roveri sobre as organizações no ciberespaço, com o caso da Wikipédia.", None),
1287: ("O livro que marca a chegada do Romantismo ao Brasil, de Gonçalves de Magalhães, publicado em Paris em 1836.", None),
565: ("Romance de Alberto Pimentel passado na Espanha de 1873, em plena agitação republicana.", None),
259: ("Reflexões de Jaime de Magalhães Lima sobre a guerra: ganhos, perdas e a revisão de valores.", None),
375: ("Jaime de Magalhães Lima retrata Alexandre Herculano, o paladino que sonhou redimir a pátria.", None),
644: ("Os Elementos de Geometria de Clairaut em português: a geometria ensinada pelo caminho da descoberta.", None),
1594: ("Novela de Herculano sobre um pároco de aldeia e a filosofia triste e árida da vida.", None),
618: ("Estudos de história literária de Garrett, incluindo o Retrato de Vênus.", "Crítica literária"),
79: ("Comédia em cinco atos sobre a juventude do poeta Bocage, por José da Silva Mendes Leal.", "Teatro"),
541: ("Guiomar, moça ambiciosa, escolhe entre três pretendentes o que lhe convém. Machado de Assis, 1874.", None),
598: ("Um sapatinho, um rapaz fascinado e a moça de pé encantador. Romance urbano de José de Alencar, 1870.", None),
579: ("O Romanceiro de Garrett: romances da Renascença recolhidos da tradição.", None),
567: ("Romance de Alberto Pimentel que começa à sombra do Bom Jesus do Monte, em Braga.", None),
587: ("Ana de Castro Osório faz um apelo às mulheres portuguesas, num momento de incerteza sobre o futuro.", None),
364: ("Lendas e contos de Rebello da Silva, entre eles a torre de Caim e o castelo de Almourol.", None),
464: ("Taunay descreve a exploração entre os rios Taquari e Aquidauana, em Mato Grosso.", "Viagem"),
224: ("Delfim Guimarães defende que Crisfal é pseudônimo do autor de Menina e Moça.", None),
1624: ("O amigo Augusto Machado publica as notas de Gonzaga de Sá, funcionário apaixonado pelo Rio antigo. Lima Barreto.", None),
1334: ("Primeira das crônicas coloniais de Alencar, com o jovem Garatuja no Rio antigo.", None),
613: ("Jacques Delille ensina em verso a arte de aformosear as paisagens e os jardins.", None),
329: ("Romance dos tempos pré-históricos, de J.-H. Rosny, na tribo de Vamiré.", None),
1827: ("Uma casinha solitária numa ilha do mar da Sicília abre este romance de Aluísio Azevedo.", None),
623: ("Castilho defende a agricultura como caminho da felicidade. Segundo volume.", None),
611: ("Castilho defende a agricultura como caminho da felicidade. Primeiro volume.", "Ciência"),
374: ("Fanny, estudo de Ernest Feydeau sobre uma paixão de adultério e ciúme, numa casa à beira-mar.", None),
494: ("Noites de Cintra, de Alberto Pimentel, impresso em 1908.", None),
569: ("Quarto volume da Comédia do Campo, de Bento Moreno: novos contos de gente da aldeia.", None),
2990: ("Comédia de Araújo Porto Alegre sobre Angélica, Firmino e uma casa cheia de pretendentes.", None),
568: ("Contos vários de Taunay, a começar numa viagem de trem entre São Paulo e o Rio.", None),
2648: ("Escritos de crítica de Machado de Assis, de 1910, abertos com um ensaio sobre a nova geração poética.", None),
1589: ("Jordanes conta a história dos godos, no século VI.", None),
550: ("Poesias eróticas, burlescas e satíricas de Bocage, o poeta mais atrevido de Portugal.", None),
2611: ("Relato da quadragésima ascensão francesa ao Monte Branco, por Paul Verne, traduzido por Salvador de Mendonça.", "Viagem"),
1693: ("Euclides da Cunha defende o Peru na disputa de limites com a Bolívia, julgada pelo governo argentino.", None),
88: ("Poema de Guerra Junqueiro contra a monarquia e os poderosos de Portugal, de 1896.", None),
110: ("Os fatos mais notáveis da história do Brasil, em ordem cronológica, do Descobrimento (1500) até 1849.", None),
238: ("As poesias de Alexandre Herculano, de A Harpa do Crente a A Semana Santa, na segunda edição de 1860.", None),
2440: ("Peça de José de Alencar, de 1858, sobre uma Madalena moderna, a Madalena do ouro.", None),
321: ("Jaime de Magalhães Lima retrata o político e orador José Estêvão.", None),
368: ("Ramalho Ortigão percorre os monumentos, a pintura e as artes industriais de Portugal e critica a indiferença oficial.", None),
1566: ("A ciência aplicada à casa, da alimentação à economia doméstica, por Eulália Vaz (1912).", None),
3909: ("Um método para aprender o tupi, escrito por Couto de Magalhães para quem convive com os indígenas.", "Ciência"),
1619: ("Scrooge e a visita de três espíritos na noite de Natal. Dickens e o espírito do Natal.", None),
422: ("Contos de António Patrício que começam num jantar no palácio vazio.", None),
1136: ("Contos de Artur de Azevedo escritos em verso, como Soror Martha e O copo.", None),
2619: ("O Fausto de Goethe, traduzido por Agostinho de Ornelas.", "Teatro"),
1386: ("Romance de Raul Pompeia sobre jogo, ambição e uma empresa arriscada.", None),
572: ("Drama de Benito Pérez Galdós, de 1901, sobre Electra, a Igreja e a liberdade de uma jovem.", None),
1629: ("Novela histórica de Herculano que começa ao toque das ave-marias numa vila medieval.", None),
580: ("O Romanceiro de Garrett: romances cavalheirescos antigos.", None),
108: ("Romance de Alfredo Campos, publicado no Porto em 1873.", None),
2533: ("Cartas satíricas em verso, atribuídas a Tomás Antônio Gonzaga, contra o governador de Minas.", "Poesia"),
433: ("As conferências de Pereira da Silva sobre Cristóvão Colombo e o descobrimento da América.", None),
511: ("Os feitos de Macau contra os piratas da China, contados em 1835.", None),
415: ("Contos de João da Câmara, publicados em 1900.", None),
520: ("As bases de uma educação nova, segundo Augusto Joaquim Alves dos Santos.", None),
3469: ("Comédia de Artur de Azevedo e Moreira Sampaio sobre uma companhia de teatro em turnê pelo interior. O Mambembe, 1904.", None),
316: ("Peça em três atos de Pinto da Rocha, com o subtítulo Evangelho.", None),
199: ("Romance de S. de Magalhães Lima, dedicado à mulher como filha, esposa e mãe.", None),
2536: ("As cartas e os ofícios que o príncipe D. Pedro enviou a D. João VI.", None),
83: ("Poesias de Gomes Leal, um dos grandes poetas satíricos de Portugal.", None),
1403: ("Aventuras de um russo, o falso doutor Bogoloff, no Brasil. Sátira de Lima Barreto.", "Romance"),
1264: ("Romance de Pardal Mallet, que começa com uma moça largando o jornal na sala.", None),
605: ("Lúcio conta a amizade com Ricardo e o mistério de uma mulher que mudou tudo. Mário de Sá-Carneiro, 1914.", None),
49: ("A crônica de el-rei D. Dinis, o Lavrador, escrita por Rui de Pina. Segundo volume.", None),
1582: ("Augusto Filipe Simões reivindica para Bartolomeu de Gusmão a invenção do balão.", "História"),
1694: ("Poema de Cláudio Manuel da Costa sobre a fundação de Vila Rica, a capital das Minas Gerais.", None),
290: ("O manuscrito de Silva Porto sobre o encontro com Livingstone, encontrado entre seus papéis.", None),
633: ("As Fábulas e as Folhas Caídas de Garrett, seus versos de amor mais famosos.", None),
3648: ("Drama histórico de Gonçalves Dias sobre Leonor de Mendonça.", None),
98: ("Miniaturas românticas de S. de Magalhães Lima, entre o drama íntimo e a comédia humana.", None),
523: ("Os versos de Soares de Passos, poeta romântico do Porto.", None),
2059: ("Novela de Raul Pompeia passada nas águas do Iapurá, no Amazonas.", "Romance"),
2900: ("Aluísio Azevedo conta o Japão, que o mundo acabava de descobrir nas crônicas japonesas.", None),
2868: ("As poesias de Bernardo Guimarães, de 1865, a começar com um canto épico.", None),
237: ("A política intercolonial e o Tratado de Lourenço Marques, por Carlos Testa.", None),
277: ("José Soares da Cunha e Costa liga a luta civil brasileira ao sebastianismo português.", None),
1277: ("Romance de Apolinário Porto-Alegre passado nos pampas do Sul.", None),
292: ("Saudades, ou História de Menina e Moça, o romance sentimental de Bernardim Ribeiro, do século XVI.", None),
293: ("Décio Carneiro estuda Sá de Miranda e sua obra.", None),
367: ("José Barbosa discute as relações luso-brasileiras, a imigração e a desnacionalização do Brasil, em 1909.", None),
1381: ("Uma história de assombração em Jordão, perto do Recife, contada por Guimarães Júnior.", None),
3967: ("Gramática da língua kiriri, escrita pelo jesuíta Luís Vincêncio Mamiani em 1699.", "Ciência"),
1995: ("Sílvio Romero recolhe contos populares do Brasil, como A combuca de ouro e os marimbondos.", None),
230: ("Hamlet de Shakespeare em cinco atos, em outra tradução para o português.", None),
1660: ("Poema de Joaquim Pereira Teixeira de Vasconcelos sobre Marános e Eleonor.", None),
344: ("História anedótica de um tratado inédito, por Luciano Cordeiro.", None),
2429: ("Alencar fecha o ciclo de As asas de um anjo com a Madalena redimida.", None),
354: ("Magalhães Lima viaja a Madri e conta os costumes madrilenos.", None),
366: ("Contos de Almáquio Diniz, publicados em Coimbra em 1911.", None),
173: ("Adolfo Caminha viaja aos Estados Unidos e conta o país dos yankees.", "Viagem"),
454: ("Adolfo Coelho apresenta os dialetos românicos da África, Ásia e América.", None),
386: ("Quadros da história portuguesa, por I. F. Silveira da Mota.", None),
}
out = []
for i, (c, t) in D.items():
    e = {"id": i, "chamada": c}
    if t:
        e["temas"] = [t]
    out.append(e)
json.dump(out, open("chamadas-6.json", "w", encoding="utf8"), ensure_ascii=False)
print(len(out), max(len(e["chamada"]) for e in out))
