import json
FARPAS = "Crônica mensal de Eça de Queirós e Ramalho Ortigão sobre a política, as letras e os costumes de Portugal."
NOITES = "Camilo Castelo Branco, nas Noites de Insônia, oferecidas a quem não pode dormir."
D = {
467: ("Camilo Castelo Branco, ao longo do rio Lima, perto de Viana do Castelo.", None),
562: ("Contos de Taunay passados no Brasil de seu tempo.", None),
106: ("A crônica de el-rei D. Afonso V, escrita por Rui de Pina. Segundo volume.", None),
241: ("A crônica de el-rei D. Afonso V, escrita por Rui de Pina. Primeiro volume.", None),
188: ("A crônica de el-rei D. Afonso V, escrita por Rui de Pina. Terceiro volume.", None),
1743: ("Pinheiro Chagas coloca os descobrimentos portugueses ao lado dos de Colombo, no centenário de 1892.", None),
282: ("Romance de Camilo Castelo Branco, na quinta edição, com notas sobre a primeira, publicada no Rio de Janeiro.", None),
2685: ("Poema épico de Santa Rita Durão sobre Diogo Álvares, o Caramuru, náufrago na Bahia, e a índia Paraguaçu.", None),
472: ("Os romances populares portugueses, reunidos em volume a partir da tradição oral.", None),
81: ("Raul Brandão escreve sobre os pobres, com carta-prefácio de Guerra Junqueiro (1906).", None),
365: ("Impressões de viagem de Maria Amália Vaz de Carvalho.", None),
554: ("As poesias completas de Machado de Assis, reunidas por ele mesmo.", None),
455: ("Crônicas de Alberto Pimentel, impressas no Porto em 1873.", None),
387: ("Notas de arte de António de Lemos, de 1904, que partem da ideia de Taine de que a arte reflete os costumes.", None),
2126: ("Ensaios de Euclides da Cunha, de 1907, a abrir com a chegada de um prisioneiro ilustre a Assunção, no tempo do Dr. Francia.", "Crônica e ensaio"),
591: ("Romance de Teixeira de Queiroz sobre a vida da gente de uma aldeia portuguesa.", None),
578: ("Alberto Pimentel conta a vida da infanta D. Joana, filha de D. Duarte, nascida póstuma em 1439 e rainha de Castela.", None),
2692: ("O Fausto de Goethe na tradução de Antônio Feliciano de Castilho.", "Teatro"),
339: ("A revolução republicana de 31 de janeiro de 1891 no Porto, contada em 1912.", None),
638: ("Diálogos de nobres numa aldeia portuguesa do século XVII sobre costumes, letras e poesia. Segundo volume.", None),
1888: ("Maria Amália Vaz de Carvalho fala da dissolução doméstica, do divórcio e da educação das crianças.", "Crônica e ensaio"),
2629: ("Romance de Adolfo Caminha, que abre com a viagem ao Rio de Janeiro, o grande e espetaculoso Rio.", None),
360: ("Romance de Paul Bourget, traduzido para português.", None),
631: ("Teófilo Braga reúne o romanceiro geral português, colhido da tradição.", None),
338: ("Romance filosófico de Camilo Castelo Branco, número 57 da edição popular de suas obras.", None),
1464: ("Poema épico de Gonçalves de Magalhães sobre a luta dos tamoios contra os portugueses (1856).", None),
462: ("Alberto Pimentel descreve as manhãs de Cascais, de onde parte o exército alado do verão.", None),
622: ("Coelho Neto conta a capital federal pelos olhos de um sertanejo recém-chegado.", None),
361: ("Camilo narra a história do carrasco José Alves, que virou personagem de Victor Hugo.", None),
3872: ("Memórias de Diana de Liz, dedicadas à amiga que partiu.", None),
570: ("Cenas do Minho, de Bento Moreno: a história de dois órfãos que perdem o pai numa manhã de maio.", None),
423: ("Lições de Psicologia e Pedologia de António Aurélio da Costa Ferreira, professor da Escola Normal de Lisboa.", "Psicologia"),
3902: ("Carolina Michaëlis estuda a infanta D. Maria, filha de D. Manuel, e o seu paço, estudos e passatempos.", None),
1147: ("Livro de poemas de Auta de Sousa, poeta potiguar morta aos 24 anos.", None),
1606: ("Adolfo Caminha viaja aos Estados Unidos e conta o país dos ianques.", "Viagem"),
1338: ("Comédia de José de Alencar sobre o casamento, de 1861.", None),
2402: ("Comédia de Araújo Porto Alegre sobre superstição e lobisomens.", None),
1262: ("Romance de Bruno Seabra.", None),
574: ("Frases célebres da história contadas de forma pitoresca por Alfredo Campos.", None),
425: ("História da Grécia, contada por Fernandes Costa.", None),
2749: ("Drama de José de Alencar sobre um padre jesuíta.", None),
1362: ("Lenda tupi de José de Alencar sobre o guerreiro Ubirajara.", "Romance"),
111: ("Cantos sagrados de Manuel de Arriaga, primeiro presidente da República Portuguesa.", None),
330: ("Caetano Alberto da Silva conta o descobrimento das Filipinas pelo navegador português Fernão de Magalhães.", None),
287: ("Os poemas de Flores do Campo, de João de Deus.", None),
441: ("Alberto Pimentel retrata um contemporâneo do infante D. Henrique.", None),
99: ("Contos de aldeia, de Alberto Leal Barradas Monteiro.", None),
3311: ("Gândavo descreve o Brasil de 1576: costa, índios e riquezas. Uma das primeiras histórias do Brasil.", None),
195: ("Notícia dos livreiros e impressores de Lisboa na segunda metade do século XVI, por Gomes de Brito.", None),
30: ("A crônica de el-rei D. Dinis, o Lavrador, escrita por Rui de Pina. Primeiro volume.", None),
82: ("Poesias inéditas de Antero de Quental, escritas entre 1859 e 1863.", None),
1331: ("Comédia de Joaquim Manuel de Macedo sobre o luxo e a vaidade.", None),
313: ("Teatro de João de Andrade Corvo, com O Aliciador e O Astrólogo.", None),
48: ("Poemas de amor do árcade Tomás Antônio Gonzaga a Marília, escritos antes da prisão.", None),
299: ("Francisco Manuel de Melo reflete sobre a influência dos descobrimentos portugueses.", None),
493: ("Dicionário de João Fernandes, com lições de língua portuguesa pelo autor.", None),
291: ("Vinte anos de experiências com eucaliptos e acácias, por Jaime de Magalhães Lima.", None),
228: ("A influência europeia na África diante da civilização e das raças, por Carlos Testa.", None),
162: ("Sátira em verso de Guerra Junqueiro que põe Deus e a Igreja em questão.", None),
1465: ("Sátira em verso de Guerra Junqueiro que põe Deus e a Igreja em questão.", None),
1749: ("Romance de Victor Leal.", None),
3084: ("Peça de teatro de João do Rio sobre a bela Madame Vargas.", None),
502: ("Ao de leve, de Brito Camacho: histórias e impressões sem pressa.", None),
620: ("O padre Rafael Bluteau ensina a cultura das amoreiras e a criação do bicho-da-seda.", None),
394: ("João Pandiá Calógeras defende o papel dos jesuítas no ensino.", None),
1436: ("Contos e textos de Machado de Assis publicados em 1910, depois de sua morte.", None),
37: ("O livro de poemas de António Nobre, escrito em Paris e cheio de saudade de Portugal.", None),
452: ("Crônicas de viagem de Alberto Pimentel.", None),
362: ("Contos do Pará, por João Marques de Carvalho.", None),
318: ("Contos do Norte do Brasil, por João Marques de Carvalho.", None),
66: ("Estudo político dedicado às classes que mandam, por Cláudio José Nunes.", None),
1974: ("A vida de Santos-Dumont contada como maravilha.", None),
434: ("Drama de Camilo Castelo Branco em três atos e quatro quadros.", None),
2392: ("Folhetim de Aluísio Azevedo, de 1885, sobre as grafias de um nome.", None),
154: ("Antonio Pereira Rebouças reúne apontamentos sobre a via de comunicação do rio Madeira.", None),
1239: ("Comédia de José de Alencar, de 1857, sobre o pajem Pedro e suas travessuras numa casa do Rio.", None),
19: ("A crônica de el-rei D. Afonso III, escrita por Rui de Pina.", None),
140: ("A crônica de el-rei D. Afonso II, escrita por Rui de Pina.", None),
1845: ("Comédia de Artur de Azevedo.", None),
1: ("Lendas gaúchas de Simões Lopes Neto, como a Salamanca do Jarau e o Negrinho do Pastoreio.", None),
275: ("Lendas dos vegetais, reunidas por Eduardo Henrique Vieira.", None),
3253: ("Contos de Edgar Allan Poe, entre o terror e o raciocínio.", None),
3118: ("Comédia de Joaquim Manuel de Macedo.", None),
56: ("Manuel da Maya e os engenheiros militares portugueses, por Christóvam Ayres.", None),
2469: ("Comédia de Joaquim Manuel de Macedo.", None),
41: ("Madalena, Manuel de Sousa Coutinho e o regresso de um peregrino: o drama de Garrett, obra-prima do teatro romântico português.", None),
584: ("Romance de Afonso Celso, sobre Lupe.", None),
1419: ("Romance de Alcântara Machado, que ficou inacabado.", None),
2061: ("Drama de José de Alencar, de 1860, sobre o amor de uma mãe escrava.", None),
262: ("Histórias vividas, de Ana de Castro Osório.", None),
359: ("Itinerário da viagem a Jerusalém feita pelo padre Francisco Guerrero.", None),
255: ("Poema de José Agostinho de Macedo em honra de Newton.", None),
2813: ("Artur de Azevedo passa em revista o Rio de Janeiro de 1877.", None),
2709: ("Lima Barreto investiga o subterrâneo do morro do Castelo, no centro do Rio.", None),
397: ("Moniz Barreto estuda a psicologia de Oliveira Martins.", None),
3019: ("Peça de Jean Crespin sobre a tragédia de Guanabara.", None),
2732: ("O Código Criminal do Império do Brasil.", None),
266: ("Romance lírico em quatro jornadas, de Augusto de Lacerda.", None),
1132: ("Comédia de França Júnior sobre as doutoras e a emancipação feminina.", None),
180: ("Sobre a prioridade dos portugueses no descobrimento do Brasil.", None),
25: ("Obras poéticas de Nicolau Tolentino de Almeida. Segundo tomo.", None),
201: ("Cidades e paisagens, por Jaime de Magalhães Lima.", None),
1916: ("Comédia de França Júnior sobre os caminhos tortos do direito.", None),
3348: ("Poesias indianistas de Machado de Assis, de 1875.", None),
1309: ("Comédia de Artur de Azevedo.", None),
1859: ("Cândido de Figueiredo em 1913, entre a língua e a gramática.", None),
1260: ("As Flores do Mal de Baudelaire, a obra que renovou a poesia do século XIX.", None),
2509: ("Conto de Machado de Assis.", None),
346: ("Rogações de eremita, poemas de Jaime de Magalhães Lima.", None),
2222: ("Poemas religiosos e patrióticos de Herculano, de 1838.", None),
1244: ("As fábulas de Esopo em português.", None),
332: ("Romance de Pinheiro Chagas, com um melodrama em Santo Tirso.", None),
453: ("Alberto Pimentel discute a importância da história universal filosófica.", None),
1341: ("Relatório de Euclides da Cunha, comissário brasileiro, sobre o reconhecimento do alto Purus.", None),
103: ("Conto de Luís da Silva Mousinho de Albuquerque sobre Rui, o escudeiro.", None),
1544: ("Dicionário biográfico dos músicos portugueses, por José Mazza.", None),
118: ("Tragédia sobre Inês de Castro, de João Baptista Gomes Júnior.", None),
1655: ("Narrativa de José de Alencar sobre o ermitão da Glória.", None),
223: ("Esboço biográfico de D. Joana de Portugal, a princesa santa, por Marques Gomes.", None),
466: ("Alberto Pimentel retrata os netos de Camilo.", None),
2014: ("O naturalista Fritz Müller defende a teoria de Darwin com observações feitas no Brasil.", None),
3266: ("Conto de Machado de Assis.", None),
3582: ("Opereta de Artur de Azevedo.", None),
}
for i in (23, 22, 8, 15, 10, 9, 13, 11, 21, 14):
    D[i] = (FARPAS, None)
for i in (305, 304, 186, 187, 261, 269, 307, 211, 213, 306, 302, 294):
    D[i] = (NOITES, None)
out = []
for i, (c, t) in D.items():
    e = {"id": i, "chamada": c}
    if t:
        e["temas"] = [t]
    out.append(e)
json.dump(out, open("chamadas-7.json", "w", encoding="utf8"), ensure_ascii=False)
print(len(out), max(len(e["chamada"]) for e in out))
